name: Python Package using Conda

class Bank:
    def __init__(self):
        self.accounts = {}

    def add_account(self, account):
        self.accounts[account.get_account_number()] = account

    def get_account(self, account_number):
        return self.accounts.get(account_number)

    def transfer_money(self, from_account_number, to_account_number, amount):
        from_account = self.get_account(from_account_number)
        to_account = self.get_account(to_account_number)

        if not from_account or not to_account:
            return "Invalid account number"

        if from_account.get_balance() < amount:
            return "Insufficient funds"

        from_account.withdraw(amount)
        to_account.deposit(amount)

        return "Transfer completed successfully"

class Account:
    def __init__(self, account_number, balance=0):
        self.account_number = account_number
        self.balance = balance

    def get_account_number(self):
        return self.account_number

    def get_balance(self):
        return self.balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
        else:
            print("Insufficient funds")

